Update run

diff --git a/root/etc/s6-overlay/s6-rc.d/aircast/run b/root/etc/s6-overlay/s6-rc.d/aircast/run
--- a/root/etc/s6-overlay/s6-rc.d/aircast/run
+++ b/root/etc/s6-overlay/s6-rc.d/aircast/run
@@ -1,49 +1,17 @@
-#!/command/execlineb -P
-nginx -g "daemon off;"
+#!/bin/sh
 
+echo "Starting aircast run"
 
-[supervisord]
-nodaemon=true
-
-[program:airupnp]
-redirect_stderr=true
-command=/bin/airupnp-linux-x86_64 -l 1000:2000
-process_name = airupnp-linux-x86_64
-
-[program:aircast]
-redirect_stderr=true
-command=/bin/aircast-linux-x86_64
-process_name = aircast-linux-x86_64
-
-
-
-
-# Get supervisor configuration lines
-UPNP=$(sed '4,7!d' /etc/supervisord.conf | grep -c '^#')
-CAST=$(sed '9,12!d' /etc/supervisord.conf | grep -c '^#')
-
-# Update supervisor configuration for airupnp based on environment variables
-# Check if VAR is empty, and assign arch / if not empty, run with command and assign arch / if kill, and hasn't run (=0) then comment out
-if [ -z "$AIRUPNP_VAR" ]; then
-  sed -i 's;command=/bin/airupnp-linux-x86_64 -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR"' -l 1000:2000;' /etc/supervisord.conf
-elif [ "$AIRUPNP_VAR" != "kill" ]; then
-  sed -i 's;command=/bin/airupnp-linux-x86_64 -l 1000:2000;command=/bin/airupnp-'"$ARCH_VAR $AIRUPNP_VAR"';' /etc/supervisord.conf
-elif [ "$AIRUPNP_VAR" = "kill" ] && [ "$UPNP" = 0 ]; then
-    for i in {4..7}
-    do
-      sed -i ''$i'{s/^/#/}' /etc/supervisord.conf
-    done
+if [ ! -f /bin/aircast-"${ARCH_VAR}" ]; then
+    echo "executable not found - exiting"
+    exit 1
+else
+    echo "file exists"
+    if [ -z "${AIRCAST_VAR}" ]; then
+       /bin/aircast-"${ARCH_VAR}"
+    else
+       /bin/aircast-"${ARCH_VAR}" "${AIRCAST_VAR}"
+    fi
 fi
 
-# Update supervisor configuration for airupnp based on environment variables
-# Check if VAR is empty, and assign arch / if not empty, run with command and assign arch / if kill, and hasn't run (=0) then comment out
-if [ -z "$AIRCAST_VAR" ]; then
-  sed -i 's;command=/bin/aircast-linux-x86_64;command=/bin/aircast-'"$ARCH_VAR"';' /etc/supervisord.conf
-elif [ "$AIRCAST_VAR" != "kill" ]; then
-  sed -i 's;command=/bin/aircast-linux-x86_64;command=/bin/aircast-'"$ARCH_VAR $AIRCAST_VAR"';' /etc/supervisord.conf
-elif [ "$AIRCAST_VAR" = "kill" ] && [ "$CAST" = 0 ]; then
-    for i in {9..12}
-    do
-      sed -i ''$i'{s/^/#/}' /etc/supervisord.conf
-    done
-fi
+echo "Exiting aircast run"
